[tools]
node = "24"
bun = "latest"
biome = "latest"
sops = "latest"
vp = "latest"

[env]
SOPS_AGE_RECIPIENTS = "age1a9p2k3u40mvdntpad4ga7akvnnqqwm6eskfr2yxkgq3u9lp7jfns2wgqty, age155th0ptdjf3gkp7pmzqcepe9kec9n3w32l87czf29fda4a2gj49ql0pg8a"
_ = { file = "{ path = .env }" }

[tasks]
encrypt = "sops -e -i .env && mv .env .env.example"
decrypt = "mv .env.example .env && sops -d -i .env"
install = "bun install"
build = "bun run build"
bot = "bun run bot:start"

[deps]
bun = { auto = true }
