import type { Context } from "probot";
import { POSTS_COLLECTION } from "$lib/server/config";

const contentPrefix = `${POSTS_COLLECTION.path}/`;

function hasContentChanges(files: { filename: string }[]): boolean {
  return files.some((f) => f.filename.startsWith(contentPrefix));
}
export async function handlePullRequest(context: Context<"pull_request">) {
  const { payload, log } = context;
  const { action, pull_request: pr, repository } = payload;

  if (pr.user?.type === "Bot") return; // ignore bot PRs

  const owner = repository.owner.login;
  const repo = repository.name;
  const prNumber = pr.number;

  switch (action) {
    case "opened":
    case "synchronize": {
      const { data: files } = await context.octokit.rest.pulls.listFiles({
        owner,
        repo,
        pull_number: prNumber,
        per_page: 100,
      });

      if (!hasContentChanges(files)) {
        log.debug({ pr: prNumber }, "No content changes in PR");
        return;
      }

      const contentFiles = files.filter((f) => f.filename.startsWith(contentPrefix));
      const summary = [
        `## 📝 LightCMS Content Review`,
        ``,
        `This PR touches **${contentFiles.length}** content file(s):`,
        ``,
        ...contentFiles.map((f) => {
          const status = f.status === "added" ? "🆕" : f.status === "removed" ? "🗑️" : "✏️";
          return `- ${status} \`${f.filename}\` (${f.changes} change${f.changes !== 1 ? "s" : ""})`;
        }),
        ``,
        `_Auto-generated by LightCMS bot._`,
      ].join("\n");

      // Check if we already left a comment
      const { data: comments } = await context.octokit.rest.issues.listComments({
        owner,
        repo,
        issue_number: prNumber,
        per_page: 100,
      });

      const botComment = comments.find(
        (c) => c.user?.type === "Bot" && c.body?.includes("LightCMS Content Review"),
      );

      if (botComment) {
        await context.octokit.rest.issues.updateComment({
          owner,
          repo,
          comment_id: botComment.id,
          body: summary,
        });
      } else {
        await context.octokit.rest.issues.createComment({
          owner,
          repo,
          issue_number: prNumber,
          body: summary,
        });
      }

      // Add a label
      const { data: labels } = await context.octokit.rest.issues.listLabelsOnIssue({
        owner,
        repo,
        issue_number: prNumber,
      });

      if (!labels.some((l) => l.name === "content")) {
        await context.octokit.rest.issues.addLabels({
          owner,
          repo,
          issue_number: prNumber,
          labels: ["content"],
        });
      }

      break;
    }

    case "closed": {
      if (pr.merged) {
        log.info(
          {
            pr: prNumber,
            mergedBy: pr.merged_by?.login,
          },
          "Content PR merged",
        );
      }
      break;
    }
  }
}
