import type { Context } from "probot";
import {
	CONTENT_LABEL,
	GITHUB_PAGE_SIZE,
	REVIEW_MARKER,
} from "../constants.js";
import { isContentPath } from "../content.js";
import { logBotError } from "./error-handler.js";

type PullRequestContext = Context<"pull_request">;

interface ContentFile {
	filename: string;
	status?: string;
	changes?: number;
}

interface BotComment {
	id: number;
	body?: string;
	userType?: string;
}

function isBotAuthor(context: PullRequestContext): boolean {
	const authorType = context.payload.pull_request.user?.type;
	return authorType === "Bot";
}

function toContentFiles(files: ContentFile[]): ContentFile[] {
	const contentFiles: ContentFile[] = [];
	for (const file of files) {
		if (isContentPath(file.filename)) {
			contentFiles.push(file);
		}
	}
	return contentFiles;
}

function describeChangeCount(changes: number | undefined): string {
	if (changes === undefined) {
		return "unknown changes";
	}
	if (changes === 1) {
		return "1 change";
	}
	return `${changes} changes`;
}

function statusIcon(status: string | undefined): string {
	if (status === "added") {
		return "🆕";
	}
	if (status === "removed") {
		return "🗑️";
	}
	return "✏️";
}

function buildReviewSummary(contentFiles: ContentFile[]): string {
	const lines: string[] = [];
	lines.push("## 📝 LightCMS Content Review");
	lines.push("");
	lines.push(`This PR touches **${contentFiles.length}** content file(s):`);
	lines.push("");
	for (const file of contentFiles) {
		const icon = statusIcon(file.status);
		const changeText = describeChangeCount(file.changes);
		lines.push(`- ${icon} \`${file.filename}\` (${changeText})`);
	}
	lines.push("");
	lines.push("_Auto-generated by LightCMS bot._");
	return lines.join("\n");
}

async function findBotCommentId(
	context: PullRequestContext,
	owner: string,
	repo: string,
	prNumber: number,
): Promise<number | undefined> {
	const { data: comments } = await context.octokit.rest.issues.listComments({
		owner,
		repo,
		issue_number: prNumber,
		per_page: GITHUB_PAGE_SIZE,
	});

	for (const comment of comments) {
		const body: string | undefined = comment.body ?? undefined;
		const userType: string | undefined = comment.user?.type ?? undefined;
		if (
			userType === "Bot" &&
			body !== undefined &&
			body.includes(REVIEW_MARKER)
		) {
			return comment.id;
		}
	}

	return undefined;
}

async function upsertReviewComment(
	context: PullRequestContext,
	owner: string,
	repo: string,
	prNumber: number,
	summary: string,
): Promise<void> {
	const existingCommentId = await findBotCommentId(
		context,
		owner,
		repo,
		prNumber,
	);

	if (existingCommentId !== undefined) {
		await context.octokit.rest.issues.updateComment({
			owner,
			repo,
			comment_id: existingCommentId,
			body: summary,
		});
		return;
	}

	await context.octokit.rest.issues.createComment({
		owner,
		repo,
		issue_number: prNumber,
		body: summary,
	});
}

async function ensureContentLabel(
	context: PullRequestContext,
	owner: string,
	repo: string,
	prNumber: number,
): Promise<void> {
	const { data: labels } = await context.octokit.rest.issues.listLabelsOnIssue({
		owner,
		repo,
		issue_number: prNumber,
	});

	for (const label of labels) {
		if (label.name === CONTENT_LABEL) {
			return;
		}
	}

	await context.octokit.rest.issues.addLabels({
		owner,
		repo,
		issue_number: prNumber,
		labels: [CONTENT_LABEL],
	});
}

async function reviewContentChanges(
	context: PullRequestContext,
): Promise<void> {
	const { payload, log } = context;
	const owner = payload.repository.owner.login;
	const repo = payload.repository.name;
	const prNumber = payload.pull_request.number;

	const { data: files } = await context.octokit.rest.pulls.listFiles({
		owner,
		repo,
		pull_number: prNumber,
		per_page: GITHUB_PAGE_SIZE,
	});

	const contentFiles = toContentFiles(files);
	if (contentFiles.length === 0) {
		log.debug({ pr: prNumber }, "No content changes in PR");
		return;
	}

	const summary = buildReviewSummary(contentFiles);
	await upsertReviewComment(context, owner, repo, prNumber, summary);
	await ensureContentLabel(context, owner, repo, prNumber);
}

/**
 * Review pull requests that touch CMS content.
 *
 * Opened and synchronized events get an idempotent summary comment plus
 * a `content` label. Merged events are logged for observability. Every
 * Octokit call is guarded so one API failure cannot crash the webhook.
 */
export async function handlePullRequest(
	context: PullRequestContext,
): Promise<void> {
	const { payload, log } = context;

	if (isBotAuthor(context)) {
		return;
	}

	const action = payload.action;

	if (action === "opened" || action === "synchronize") {
		try {
			await reviewContentChanges(context);
		} catch (error) {
			logBotError(context, "Failed to review content pull request", error);
		}
		return;
	}

	if (action === "closed") {
		if (payload.pull_request.merged) {
			log.info(
				{
					pr: payload.pull_request.number,
					mergedBy: payload.pull_request.merged_by?.login,
				},
				"Content PR merged",
			);
		}
		return;
	}

	log.debug({ action }, "Ignoring unsupported pull request action");
}

// Re-exported for unit testing without reaching into module internals.
export const __testing = {
	isContentFileForReview: isContentPath,
	buildReviewSummary,
	toContentFiles,
};

export type { BotComment };
