export const commandStrings = {
	undo: "Undo",
	redo: "Redo",
	h1: "Heading 1",
	h2: "Heading 2",
	h3: "Heading 3",
	h4: "Heading 4",
	link: "Link",
	paragraph: "Paragraph",
	bold: "Bold",
	italic: "Italic",
	underline: "Underline",
	strikethrough: "Strikethrough",
	blockQuote: "BlockQuote",
	code: "Inline Code",
	codeBlock: "Code Block",
	superscript: "Superscript",
	subscript: "Subscript",
	alignLeft: "Align Left",
	alignCenter: "Align Center",
	alignRight: "Align Right",
	alignJustify: "Align Justify",
	bulletList: "Bullet List",
	orderedList: "Ordered List",
	taskList: "Task List",
	imagePlaceholder: "Image Placeholder",
	videoPlaceholder: "Video Placeholder",
	audioPlaceholder: "Audio Placeholder",
	iframePlaceholder: "Iframe Placeholder",
	table: "Table",
	inlineExpression: "Inline Expression",
	blockExpression: "Block Expression",
	horizontalRule: "Horizontal Rule",
	mermaidDiagram: "Mermaid Diagram",
	formatGroup: "Format",
	insertGroup: "Insert",
};
