export const menuStrings = {
	link: {
		open: "Open Link",
		edit: "Edit Link",
		copy: "Copy Link",
		remove: "Remove Link",
		save: "Save",
		enterLinkPlaceholder: "Type or paste a link",
		enterLinkButton: "Set new link",
	},
	math: {
		enterExpressionPlaceholder: "Enter Math Expression",
	},
	table: {
		headerColumn: "Header Column",
		addColumnAfter: "Add Column After",
		addColumnBefore: "Add Column Before",
		moveColumnLeft: "Move Column Left",
		moveColumnRight: "Move Column Right",
		deleteColumn: "Delete This Column",
		headerRow: "Header Row",
		addRowAfter: "Add Row After",
		addRowBefore: "Add Row Before",
		moveRowUp: "Move Row Up",
		moveRowDown: "Move Row Down",
		deleteRow: "Delete This Row",
	},
};

export const toolbarStrings = {
	alignment: {
		buttonTitle: "Alignment",
		dropdownTitle: "Alignments",
	},
	color: {
		buttonTitle: "Quick Colors",
		textColor: "Text Color",
		textColors: "Text Colors",
		highlightColor: "Highlight Color",
		highlightColors: "Highlight Colors",
		templateCharacter: "A",
		default: "Default",
		blue: "Blue",
		red: "Red",
		brown: "Brown",
		green: "Green",
		gray: "Gray",
		orange: "Orange",
		pink: "Pink",
		purple: "Purple",
		yellow: "Yellow",
	},
	font: {
		buttonTitle: "Font Size",
		dropdownTitle: "Font Size",
		tiny: "Tiny",
		smaller: "Smaller",
		small: "Small",
		default: "Default",
		large: "Large",
		extraLarge: "Extra Large",
	},
	heading: {
		buttonTitle: "Headings",
	},
	link: {
		buttonTitle: "Link",
		insertLinkPlaceholder: "Insert Link",
		insertLink: "Insert Link",
	},
	list: {
		buttonTitle: "Lists",
		dropdownTitle: "Lists",
	},
	searchAndReplace: {
		buttonTitle: "Search and Replace",
		showMore: "Show More",
		goBack: "Go Back",
		searchAndReplace: "Search and Replace",
		searchPlaceholder: "Search...",
		caseSensitive: "Case Sensitive",
		goToPrevious: "Go to Previous",
		goToNext: "Go to Next",
		previous: "Previous",
		next: "Next",
		replacePlaceholder: "Replace...",
		replace: "Replace",
		replaceAll: "Replace All",
	},
};
